[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
EditorStartupMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/LowTide.LowTideGameMode

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11
+D3D11TargetedShaderFormats=PCD3D_SM5

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=0
r.Shadow.Virtual.Enable=0
r.Nanite.ProjectEnabled=False
r.RayTracing=False
r.DefaultFeature.MotionBlur=False

[/Script/Engine.Engine]
bUseFixedFrameRate=False

; Reserve memory for the editor on the 16 GB development machine.

[DevOptions.Shaders]
NumUnusedShaderCompilingThreads=14
NumUnusedShaderCompilingThreadsDuringGame=14
PercentageUnusedShaderCompilingThreads=87
